<footer id="footer">
    <div id="footer-bottom">
        <div class="container">
            <div class="eight columns">Copyright SSBLA
                2013.</div>
            <ul class="footer-nav">
                <li>See more at:</li>
                <li><a href="http://www.flickr.com/groups/SSBLA" target="_new"><i class="icos-flickr"></i></a></li>
                <li><a href="http://twitter.com/themariocup" target="_new"><i class="icos-twitter"></i></a></li>
            </ul>
        </div>
    </div>
</footer>