<!-- Required Scripts -->
<script src="/assets/js/jquery-1.8.3.min.js"></script>
<script src="/assets/js/jquery.plugins.min.js"></script>
<script src="/assets/js/bootstrap.min.js"></script>

<!-- Plugins -->
<script src="/assets/plugins/selectnav/selectnav.min.js"></script>
<script src="/assets/plugins/tweet/jquery.tweet.js"></script>
<script src="/assets/plugins/jflickrfeed/jflickrfeed.min.js"></script>
<script src="/assets/plugins/fitvids/jquery.fitvids.js"></script>
<script src="/assets/plugins/isotope/jquery.isotope.min.js"></script>
<script src="/assets/plugins/sharrre/jquery.sharrre-1.3.4.min.js"></script>

<script src="/assets/plugins/flexslider/jquery.flexslider-min.js"></script>
<link rel="stylesheet"
    href="/assets/plugins/flexslider/flexslider.css">

<script src="/assets/plugins/nivo/jquery.nivo.slider.pack.js"></script>
<link rel="stylesheet" href="/assets/plugins/nivo/nivo-slider.css">

<script src="http://maps.google.com/maps/api/js?sensor=true"></script>
<script src="/assets/plugins/map/jquery.ui.map.min.js"></script>

<script
    src="/assets/plugins/revolutionslider/js/jquery.themepunch.revolution.min.js"></script>
<link rel="stylesheet"
    href="/assets/plugins/revolutionslider/css/settings.css">

<script
    src="/assets/plugins/caroufredsel/jquery.carouFredSel-6.1.0-packed.js"></script>
<script src="/assets/plugins/caroufredsel/jquery.touchSwipe.min.js"></script>

<!-- Template Script -->
<script src="/assets/js/template.js"></script>
<script src="/assets/js/customizer.js"></script>